// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using S00250043_ConsoleApp;

#nullable disable

namespace S00250043_ConsoleApp.Migrations
{
    [DbContext(typeof(ConsoleEcommerceContext))]
    partial class ConsoleEcommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("S00250043_ClassLibrary.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Category_id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Category_id = 1,
                            Name = "Trading Cards"
                        },
                        new
                        {
                            Category_id = 2,
                            Name = "Action Figures"
                        });
                });

            modelBuilder.Entity("S00250043_ClassLibrary.Order", b =>
                {
                    b.Property<int>("Order_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_id"));

                    b.Property<string>("Order_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total_price")
                        .HasColumnType("float");

                    b.Property<int>("User_id")
                        .HasColumnType("int");

                    b.HasKey("Order_id");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Order_id = 101,
                            Order_status = "Shipped",
                            Payment_status = "Paid",
                            Total_price = 120.0,
                            User_id = 1
                        },
                        new
                        {
                            Order_id = 102,
                            Order_status = "Processing",
                            Payment_status = "Pending",
                            Total_price = 175.5,
                            User_id = 2
                        });
                });

            modelBuilder.Entity("S00250043_ClassLibrary.OrderData", b =>
                {
                    b.Property<int>("Order_item_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Order_item_id"));

                    b.Property<int>("Collectible_id")
                        .HasColumnType("int");

                    b.Property<int>("Order_id")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Unit_price")
                        .HasColumnType("float");

                    b.HasKey("Order_item_id");

                    b.ToTable("OrderData");

                    b.HasData(
                        new
                        {
                            Order_item_id = 1,
                            Collectible_id = 1,
                            Order_id = 101,
                            Quantity = 1,
                            Unit_price = 120.0
                        },
                        new
                        {
                            Order_item_id = 2,
                            Collectible_id = 2,
                            Order_id = 102,
                            Quantity = 1,
                            Unit_price = 80.0
                        },
                        new
                        {
                            Order_item_id = 3,
                            Collectible_id = 3,
                            Order_id = 102,
                            Quantity = 1,
                            Unit_price = 95.5
                        });
                });

            modelBuilder.Entity("S00250043_ClassLibrary.Product", b =>
                {
                    b.Property<int>("Collectible_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Collectible_id"));

                    b.Property<int>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock_quantity")
                        .HasColumnType("int");

                    b.HasKey("Collectible_id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Collectible_id = 1,
                            Category_id = 1,
                            Condition = "Mint",
                            Name = "Pikachu Holo Card",
                            Price = 120.0,
                            Stock_quantity = 5
                        },
                        new
                        {
                            Collectible_id = 2,
                            Category_id = 2,
                            Condition = "Good",
                            Name = "Batman Figure",
                            Price = 80.0,
                            Stock_quantity = 3
                        },
                        new
                        {
                            Collectible_id = 3,
                            Category_id = 2,
                            Condition = "Near Mint",
                            Name = "Yoda Figure",
                            Price = 95.5,
                            Stock_quantity = 2
                        });
                });

            modelBuilder.Entity("S00250043_ClassLibrary.User", b =>
                {
                    b.Property<int>("User_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User_id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("User_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            User_id = 1,
                            Email = "alice@example.com",
                            Name = "Alice Carter",
                            Role = "Customer"
                        },
                        new
                        {
                            User_id = 2,
                            Email = "bob@example.com",
                            Name = "Bob Nguyen",
                            Role = "Customer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
